AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Library Project - Book Search API

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod
    Description: Deployment environment

  BucketName:
    Type: String
    Description: S3 bucket name for book storage

  LogLevel:
    Type: String
    Default: debug
    AllowedValues:
      - debug
      - info
      - error
    Description: Application log level

Globals:
  Function:
    Runtime: nodejs24.x
    Architectures:
      - arm64
    MemorySize: 1024
    Timeout: 30
    Environment:
      Variables:
        NODE_ENV: !Ref Environment
        LOG_LEVEL: !Ref LogLevel

Resources:
  # HTTP API Gateway
  LibraryHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref Environment
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowHeaders:
          - '*'
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        MaxAge: 600

  # Lambda Function for Book Search
  GetBooksFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2022
        Sourcemap: false
        EntryPoints:
          - handler.ts
        External:
          - '@aws-sdk/client-s3'
          - '@aws-sdk/client-dynamodb'
          - '@aws-sdk/lib-dynamodb'
          - '@aws-sdk/client-lambda'
    Properties:
      FunctionName: !Sub library-get-books-${Environment}
      CodeUri: ./services/sls-get-books/
      Handler: handler.getBooks
      Description: Lambda buscar en S3 los libros solicitados y verifica en dynamo si
        existen, si no invoca al scraper para realizar la busqueda
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName
          TABLE_BOOKS: !Ref BookTable
          LAMBDA_SCRAPER_WORKER: !Ref ScraperWorkerFunction
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref BucketName
        - DynamoDBReadPolicy:
            TableName: !Ref BookTable
        - LambdaInvokePolicy:
            FunctionName: !Ref ScraperWorkerFunction
      Events:
        GetBooksApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref LibraryHttpApi
            Path: /
            Method: GET

  ScraperWorkerFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2022
        Sourcemap: false
        EntryPoints:
          - handler.ts
        External:
          - '@aws-sdk/client-sqs'
          - '@aws-sdk/client-ssm'
    Properties:
      FunctionName: !Sub library-scraper-worker-${Environment}
      CodeUri: ./services/sls-scraper-books/
      Handler: handler.scrapeBooks
      Description: worker que es invocado por la lambda GetBooksFunction para realiza
        la busqueda de los libros solicitados en la web
      Environment:
        Variables:
          SCRAPER_HOST: /library/scraper-host
          SCRAPER_PASSWORD: /library/scraper-password
          SCRAPER_USERNAME: /library/scraper-username
          SCRAPER_PORT: /library/scraper-port
          SQS_URL: !Ref SimpleQueueService
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !Ref SimpleQueueService
        - SSMParameterReadPolicy:
            ParameterName: library/*


  DataIngestorFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2022
        Sourcemap: false
        EntryPoints:
          - handler.ts
        External:
          - '@aws-sdk/client-s3'
          - '@aws-sdk/client-dynamodb'
          - '@aws-sdk/lib-dynamodb'
          - '@aws-sdk/client-lambda'
          - '@aws-sdk/client-sqs'
    Properties:
      FunctionName: !Sub library-data-ingestor-${Environment}
      CodeUri: ./services/sls-data-ingestor/
      Handler: handler.ingest
      Description: Lambda que se encarga de sobreescribir los indices de S3 y Agregar
        los libros nuevos a DynamoDB
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName
          TABLE_BOOKS: !Ref BookTable
          SQS_NAME: !Ref SimpleQueueService
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref BucketName
        - DynamoDBCrudPolicy:
            TableName: !Ref BookTable
        - LambdaInvokePolicy:
            FunctionName: !Ref ScraperWorkerFunction
      Events:
        SqsIngestEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt SimpleQueueService.Arn
            BatchSize: 10

  # DynamoDB Table for Book Storage          
  BookTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub table-books-${Environment}
      AttributeDefinitions:
        - AttributeName: isbn
          AttributeType: S
      KeySchema:
        - AttributeName: isbn
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true

  #Simple Queue Services
  SimpleQueueService:
    Type: AWS::SQS::Queue
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      QueueName: !Sub library-sqs-${Environment}
      VisibilityTimeout: 60
      MaximumMessageSize: 262144
      MessageRetentionPeriod: 345600
      ReceiveMessageWaitTimeSeconds: 10
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
        maxReceiveCount: 3

  DeadLetterQueue:
    Type: AWS::SQS::Queue
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      MessageRetentionPeriod: 345600
      QueueName: !Sub library-dlq-${Environment}

Outputs:
  ApiEndpoint:
    Description: HTTP API endpoint URL
    Value: !Sub https://${LibraryHttpApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}
    Export:
      Name: !Sub ${AWS::StackName}-ApiEndpoint

  GetBooksFunctionArn:
    Description: GetBooks Lambda Function ARN
    Value: !GetAtt GetBooksFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-GetBooksFunctionArn

  GetBooksFunctionName:
    Description: GetBooks Lambda Function Name
    Value: !Ref GetBooksFunction
    Export:
      Name: !Sub ${AWS::StackName}-GetBooksFunctionName